############################# APM Server ######################################
apm-server:
  # Defines the host and port the server is listening on
  host: "0.0.0.0:8200"

#================================ Outputs =====================================
# Configure what output to use when sending the data collected by the beat.
#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: "changeme"
