---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"
elasticsearch.url: http://elasticsearch:9200

## X-Pack functions
## see https://www.elastic.co/subscriptions
#
xpack.license.self_generated.type: basic